[project]
name = "open"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "pillow",
    "numpy",
    "pymupdf",
    "transformers>=5.9.0",
    "paddleocr>=3.4.1",
    "torch>=2.8.0",
    "python-dotenv",
    "uvicorn",
    "paddlepaddle>=3.3.1",
    "paddlepaddle-gpu",
    "rapidfuzz",
    "vllm==0.10.2",
]
